### ISSUE TITLE
danluu.com RSS feed only sort-of works

### ISSUE THREAD

**Issue by ap** [danluu/dump#2]
See <http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Fdanluu.com%2Fatom.xml>

(I will not comment on `atom.xml` being the only valid URL for a feed that’s actually in RSS. 😊)

(Also, please excuse this very stupid approach for contacting you. I would have preferred to send you email, but you seem to wish to keep your email private (fair enough); and while you advertise your Twitter handle, I cannot send you a Twitter DM and am not willing do this via public Twitter. I hope this fallback is not too much of a bother.)

**Comment by danluu** [comment]
Hi! Thanks for the bug report. I'll look into this, but fixing blog generator stuff is pretty low down on the list compared to writing new posts, so it might be a while unless there's a trivial fix.

I can think of one thing that might work, but it may have some negative side effects for other parts of the site, so I'll have to poke around a bit before trying it.

**Comment by danluu** [comment]
After one tweak, all but two errors are gone: http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Fdanluu.com%2Fatom.xml. Page load time via clicking links (as measured by webpagetest.org) is up slightly, so I may change this back, but this seems ok for now.

Are there any particular feed readers that were broken with the old version?

**Comment by ap** [comment]
Liferea was broken with the previous form of the feed:

* It doesn’t expect to have to resolve the `<link>` URL, so it ends up turning them into `file://` links, and clicking through to the site doesn’t work. (And there’s no specification for what should be used as a base URL for resolving those links: is it the URL of the feed itself? Or the one from the `<link>` item in the `<channel>`? Or something else? There’d be no difference in your case but this is not true for all feeds.)

* It failed to recognise previously-seen items when you changed your links to not include the scheme, because it compares GUIDs as simple strings.

----

I’m baffled as to how this would affect page load times when clicking. The only cause I can think of is the couple bytes added to every link… if you fixed the feed by changing a setting that also affects how your HTML pages get generated. That would imply that your site generator (or your particular config for it) couples the wrong things together. Feeds (and particularly GUIDs) have very different requirements from HTML pages and should be handled separately.

**Comment by danluu** [comment]
Hugo couples a lot of things together pretty tightly in a way that requires editing the source (as opposed to data/config files) to change. If you can get them to change that, please do :-).
